opensearch-project/opensearch-net

- tests/Tests/Tests.csproj
- tests/Tests/packages.lock.json
Signed-off-by: Yury Fridlyand <yuryf@bitquilltech.com>
- Bump SharpZipLib from 1.0.0-alpha2 to 1.3.3 in /tests/Tests
- Bump System.Net.Http from 4.3.2 to 4.3.4 in /tests/Tests
package.lock.json is also updated.
No tests affected
[List any issues this PR will resolve]
> Follow dependabot recommendation to update dependencies

- README.md
Signed-off-by: Guian Gumpac <guiang@bitquilltech.com>
Added OSC intructions to README and indicated that OSC is the OpenSearch version of NEST
> Added OSC intructions to README

- .github/workflows/integration.yml
- COMPATIBILITY.md
- README.md
Signed-off-by: Vacha Shah <vachshah@amazon.com>
Adding a compatibility matrix for the client. Also adding OpenSearch 1.3.1 to the test workflow matrix.
#26 
> Adding a compatibility matrix

- .github/workflows/compile.yml
- .github/workflows/integration.yml
- .github/workflows/release.yml
- .github/workflows/test-jobs.yml
- global.json
Update dotnet version used from 5.0.100 to 5.0.405
This change needs to be backported to 1.x and 2.x branches.
#52 
> Update dotnet version to 5.0.405

- Directory.Build.props
Setting version for all packages to 1.0.0 so that the first available version on nuget.org is 1.0.0 instead of 1.0.1.
> Revert package version to 1.0.0

- .github/workflows/integration.yml
Signed-off-by: Yury Fridlyand <yuryf@bitquilltech.com>
Remove `OpenDistro` integration tests, because it was archived and not available anymore for testing.
Fixes failing GHA integration workflow.
> Remove OpenDistro integration tests

- .github/CODEOWNERS
- MAINTAINERS.md
- Cleanup maintainers list to reflect the reality of who has permissions on the repository. 
- Add @dblock, @VachaShah, @Xtansia & @MaxKsyunz as maintainers
- Update maintainer responsibilities and process from https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md
- Update CODEOWNERS
> Add @dblock, @VachaShah, @Xtansia & @MaxKsyunz as maintainers

- CHANGELOG.md
- abstractions/src/OpenSearch.OpenSearch.Ephemeral/OpenSearch.OpenSearch.Ephemeral.csproj
- abstractions/src/OpenSearch.OpenSearch.Ephemeral/Tasks/IClusterComposeTask.cs
- abstractions/src/OpenSearch.OpenSearch.Ephemeral/packages.lock.json
- abstractions/src/OpenSearch.OpenSearch.Xunit/packages.lock.json
- abstractions/tests/OpenSearch.OpenSearch.EphemeralTests/packages.lock.json
- abstractions/tests/OpenSearch.Stack.ArtifactsApiTests/packages.lock.json
- tests/Tests.Auth.AwsSigV4/packages.lock.json
- tests/Tests.ClusterLauncher/packages.lock.json
- tests/Tests.Core/packages.lock.json
- tests/Tests.Reproduce/packages.lock.json
- tests/Tests.ScratchPad/packages.lock.json
- tests/Tests/packages.lock.json
Mitigates the following vulnerabilities:
- https://devhub.checkmarx.com/cve-details/CVE-2021-32840/
- https://devhub.checkmarx.com/cve-details/CVE-2021-32842/ 
Attack surface for these in our use case is very minimal as the library is only used via integration test code. Additionally we only ever try to extract the OpenSearch distro artifacts, so would require MITM/compromise of upstream OpenSearch or already having filesystem access.
> Bump SharpZipLib from 1.0.7 to 1.4.1

- CHANGELOG.md
- OpenSearch.sln
- USER_GUIDE.md
- src/OpenSearch.Net.Auth.AwsSigV4/AwsSigV4HttpClientHandler.cs
- src/OpenSearch.Net.Auth.AwsSigV4/AwsSigV4HttpConnection.cs
- src/OpenSearch.Net.Auth.AwsSigV4/AwsSigV4Util.cs
- src/OpenSearch.Net.Auth.AwsSigV4/CanonicalRequest.cs
- src/OpenSearch.Net.Auth.AwsSigV4/HeaderNames.cs
- src/OpenSearch.Net.Auth.AwsSigV4/OpenSearch.Net.Auth.AwsSigV4.csproj
- src/OpenSearch.Net.Auth.AwsSigV4/packages.lock.json
- tests/Tests.Auth.AwsSigV4/AwsSigV4HttpConnectionTests.cs
- tests/Tests.Auth.AwsSigV4/CanonicalRequestTests.cs
- tests/Tests.Auth.AwsSigV4/Utils/FixedDateTimeProvider.cs
- tests/Tests.Auth.AwsSigV4/Utils/HttpRequestMessageAssertions.cs
- tests/Tests.Auth.AwsSigV4/Utils/MockHttpMessageHandler.cs
- tests/Tests.Auth.AwsSigV4/Utils/TestableAwsSigV4HttpConnection.cs
- tests/Tests.Auth.AwsSigV4/packages.lock.json
Support AwsSigV4 signing for Amazon OpenSearch Serverless
- Make the service ID customizable, so it can be set to "aoss" for serverless
- Include the x-amz-content-sha256 header
- Don't sign the content-length header
Relates to #129, however does not solve documenting of methods unsupported by serverless.
> Support AwsSigV4 signing for Amazon OpenSearch Serverless

- CHANGELOG.md
- src/OpenSearch.Client/Aggregations/AggregateFormatter.cs
- tests/Tests.Reproduce/GitHubIssue130.cs
Fixes the parsing of DateHistogramBuckets. The key was incorrectly being read as a long, when it should be a double. As can be seen here, the type parameter to `KeyedBucket` is `double`: https://github.com/opensearch-project/opensearch-net/blob/main/src/OpenSearch.Client/Aggregations/Bucket/DateHistogram/DateHistogramBucket.cs#LL34C51-L34C51
And response body from server looks like so:
```json
{
"_shards": {
"failed": 0,
"skipped": 0,
"successful": 1,
"total": 1
},
"aggregations": {
"histogram#aggregation_ranges": {
"buckets": [
{
"doc_count": 1,
"key": 1672871085000.0,
"key_as_string": "2023-01-04T22:24:45.000Z"
}
]
}
},
"hits": {
"hits": [],
"max_score": null,
"total": {
"relation": "eq",
"value": 1
}
},
"timed_out": false,
"took": 90
}
```
Fixes #130 
By submitting this pull request, I …
> Fix parsing of DateHistogramBucket key

- .github/workflows/release-drafter.yml
- CHANGELOG.md
- RELEASING.md
- jenkins/release.jenkinsFile
Putting the PR in draft until dependent PRs are merged. Feel free to review till then. 
This change onboards the opensearch-net client to universal release/1-click release process. See https://github.com/opensearch-project/opensearch-build/issues/1234 for more details.
Due to the complexity of the way dotnet client is build and packaged, we considered building the client on the release CI system is the best way to go ahead. See https://github.com/opensearch-project/opensearch-build/issues/2965 for more details.
See how the underlying library is publishing to nuget https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/publishToNuget.groovy
The mentioned docker image: `opensearchstaging/ci-runner:release-centos7-clients-v2.3` (PR pending merge …
> Onboard to 1-click release process

- jenkins/release.jenkinsFile
The 2.1.1 includes a bug fix due to which previous release workflow run failed
See release details: https://github.com/opensearch-project/opensearch-build-libraries/releases/tag/2.1.1
TL;DR: The signer client is cloned in another workspace of jenkins and hence needs to be given an absolute path rather than relative.
_List any issues this PR will resolve, e.g. Closes [...]._ 
> Increment jenkins lib version to 2.1.1

- jenkins/release.jenkinsFile
Bumps jenkins library version to 2.1.2 that contains refactored code for pushing nupkg packages to Nuget. https://github.com/opensearch-project/opensearch-build-libraries/releases/tag/2.1.2
related https://github.com/opensearch-project/opensearch-build/issues/3194
> Increment jenkins library version to accommodate a bug-fix

- .github/workflows/integration.yml
- abstractions/src/OpenSearch.OpenSearch.Managed/OpenSearchNode.cs
- abstractions/src/OpenSearch.Stack.ArtifactsApi/Products/OpenSearchPlugin.cs
- tests/Tests.Core/ManagedOpenSearch/Clusters/ReadOnlyCluster.cs
- tests/Tests.Core/ManagedOpenSearch/Clusters/WritableCluster.cs
Installs the k-NN plugin for unreleased OpenSearch integration tests. Also corrects knn lib dir for 1.3.10+.
Fixes CI failures seen on merging k-NN feature: https://github.com/opensearch-project/opensearch-net/actions/runs/5373470729
> Install k-NN plugin for unreleased OpenSearch integration tests

- CHANGELOG.md
- tests/Tests.ScratchPad/Tests.ScratchPad.csproj
- tests/Tests.ScratchPad/packages.lock.json
Backport 2addb03743eadbe5355efdf022dbec5251e0b9db from #219
> [Backport 1.x] Bump BenchMarkDotNet from 0.13.4 to 0.13.5

- CHANGELOG.md
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
- tests/Tests.YamlRunner/packages.lock.json
- tests/Tests/Tests.csproj
- tests/Tests/packages.lock.json
Backport e08b5c32efdf96754d4133ae5e06ec814539c346 from #223
> [Backport 1.x] Bump FSharp.Core from 6.0.7 to 7.0.300

- .github/bump-version.sh
- .github/workflows/bump-version.yml
Adds a workflow that can be manually run to create version bump PRs.
Not fully automated off tag push as we don't pre-emptively branch the (e.g) `1.4` branch to do patch increases, as well as our release throughput being generally low. And is more useful for doing minor bump on `1.x` and major bump on main.
Can be further automated in future.
> Add bump-version workflow

- jenkins/release.jenkinsFile
We recently upgraded the python version in the build repo. Due to this any code using build repo code fails if right python version is not used. Signing artifacts used by net client uses the build repo code hence updating the image to most recent one.
https://github.com/opensearch-project/opensearch-build/issues/3712
> Update jenkins file to use new docker image

- CHANGELOG.md
- tests/Tests.Core/Tests.Core.csproj
Backport b3312fcfcdf33f102837a0a984b0f781ec5e4acb from #271
> [Backport 1.x] Bump Microsoft.TestPlatform.ObjectModel from 17.5.0 to 17.6.3

- USER_GUIDE.md
- tests/Tests.Reproduce/GitHubIssue281.cs
- Updates `USAGE.md` to demonstrate use of `IsVerbatim`/`Verbatim()` to include `TermQuery`s with non-null empty string values
- Adds test cases to demonstrate the expected behavior observed and discovered while investigating GH-281
Resolves GH-281
Signed-off-by: David Alpert <david@spinthemoose.com>
> GH-281 TermQuery with a string.Empty value needs .Verbatim() or it is ignored as "conditionless"

- CHANGELOG.md
- src/OpenSearch.Client/Search/Search/Highlighting/Highlight.cs
- src/OpenSearch.Client/Search/Search/Highlighting/HighlightField.cs
- tests/Tests/Search/Request/HighlightingUsageTests.cs
- tests/Tests/Search/Request/HighlightingUsageTestsWithMaxAnalyzerOffset.cs
Fix field `max_analyzed_offset` to `max_analyzer_offset`  
The current field `max_analyzed_offset` used in ElasticSearch doesn't match the field added to OpenSearch version 2.2.0, `max_analyzer_offset`.
This means the current client implementation have two problems:
It doesn't work for versions before version 2.2.0, because no equivalent field exist on OpenSearch.
It doesn't work for version after 2.2.0, because the field is misspelled.
Even though the Property changes, which is normally a breaking change, since the current field is unusable, this change is not "breaking" anything.
For further information see:
- https://github.com/opensearch-project/opensearch-java/pull/555
- https://github.com/opensearch-project/OpenSearch/pull/4031
- …
> Fixes #321: fix highlight max_analyzer_offset field name to match OS 2.2.0

- CHANGELOG.md
- tests/Tests.Core/Tests.Core.csproj
Backport 828ae3aca8d83d90ae8aba90d3727b991f999273 from #326 
> [Backport 1.x] Bump Microsoft.TestPlatform.ObjectModel from 17.6.3 to 17.7.1 (#326)

- CHANGELOG.md
- src/OpenSearch.Client/Search/Search/SearchResponse.cs
Fixes `NullReferenceException` when accessing `SearchResponse<TDocument>.Total` property if `TrackTotalHits` is `false`.
None
> Fix null-ref exception when track total hits is disabled

- CHANGELOG.md
- tests/Tests.Core/Tests.Core.csproj
Backports b54e353f0c92f5f316b3b6ee0947e85a4284067e from #345 
> [Backport 1.x] Bump Microsoft.TestPlatform.ObjectModel from 17.7.1 to 17.7.2 (#345)

- CHANGELOG.md
Correct CHANGELOG in main post v1.5.0 release
> Correct CHANGELOG post v1.5.0 release

- guides/index-template.md
This file is a comprehensive guide on how to use index templates with the OpenSearch .NET client. It targets the OpenSearch.Net low-level client and provides a variety of examples that demonstrate how to create, retrieve, delete, and use index templates in different scenarios. The file also includes important notes on the state of both low & high level clients at the time it was written.
The key sections of the guide include:
• Setup: Instructions for setting up a connection to an OpenSearch server running on the local machine.
• Index Template API Actions: Details on how to interact with the Index Template API to create and use index templates that match certain patterns. It demonstrates scenarios of using single and multiple templates, and how template priority affects the settings …
> Added new guide for using index templates with the low-level client

- guides/document_lifecycle.md
This PR provides add the API guide on using OpenSearch.NET client to implement document lifecycle API(s).
- Setup: Guide on setting up a local OpenSearch client instance and creating an index named ﻿movies with properties such as director, title, and year.
-
- Create a new document with specified ID: Details on how to use 'Create' or 'Index' API actions to establish new documents with preset IDs. Explains the difference regarding idempotency - 'Create' is not idempotent while 'Index' is.
- Create a new document with auto-generated ID: Instructions on using the 'Index' action to generate new documents with auto-generated IDs.
- Get a document: Tutorial on how to use the 'Get' API action to retrieve a document from the index, including how to specify which fields to include or exclude.
- …
> Added API guide for document lifecycle.

- Directory.Build.props
Treat MSBuild warnings as errors
Fixes #145 
> Treat MSBuild warnings as errors

- tests/Tests/Cluster/RemoteInfo/RemoteInfoApiTests.cs
Fixes the RemoteInfoApiTests that were failing due to changes to security plugin in 2.9+.
Fixes #311 
> Fix RemoteInfoApiTests

- CHANGELOG.md
- guides/index-template.md
- src/ApiGenerator/Configuration/CodeConfiguration.cs
- src/OpenSearch.Client/Cluster/ComponentTemplate/ComponentTemplate.cs
- src/OpenSearch.Client/Cluster/ComponentTemplate/ComponentTemplateExistsRequest.cs
- src/OpenSearch.Client/Cluster/ComponentTemplate/DeleteComponentTemplateRequest.cs
- src/OpenSearch.Client/Cluster/ComponentTemplate/DeleteComponentTemplateResponse.cs
- src/OpenSearch.Client/Cluster/ComponentTemplate/GetComponentTemplateRequest.cs
- src/OpenSearch.Client/Cluster/ComponentTemplate/GetComponentTemplateResponse.cs
- src/OpenSearch.Client/Cluster/ComponentTemplate/PutComponentTemplateRequest.cs
- src/OpenSearch.Client/Cluster/ComponentTemplate/PutComponentTemplateResponse.cs
- src/OpenSearch.Client/_Generated/ApiUrlsLookup.cs
- src/OpenSearch.Client/_Generated/Descriptors.Cluster.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.Cluster.cs
- src/OpenSearch.Client/_Generated/Requests.Cluster.cs
- src/OpenSearch.Net/Api/RequestParameters/RequestParameters.Cluster.cs
- src/OpenSearch.Net/OpenSearchLowLevelClient.Cluster.cs
- src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Cluster.cs
- src/OpenSearch.Net/_Generated/OpenSearchLowLevelClient.Cluster.cs
- tests/Tests/Cluster/ComponentTemplate/ComponentTemplateCrudTests.cs
- tests/Tests/Cluster/ComponentTemplate/ComponentTemplateExistsApiTests.cs
- tests/Tests/Cluster/ComponentTemplate/ComponentTemplateExistsUrlTests.cs
- tests/Tests/Cluster/ComponentTemplate/DeleteComponentTemplateApiTests.cs
- tests/Tests/Cluster/ComponentTemplate/DeleteComponentTemplateUrlTests.cs
- tests/Tests/Cluster/ComponentTemplate/GetComponentTemplateApiTests.cs
- tests/Tests/Cluster/ComponentTemplate/GetComponentTemplateUrlTests.cs
- tests/Tests/Cluster/ComponentTemplate/PutComponentTemplateApiTests.cs
- tests/Tests/Cluster/ComponentTemplate/PutComponentTemplateUrlTests.cs
- tests/Tests/CodeStandards/NamingConventions.doc.cs
- tests/Tests/Tests.csproj
Adds support for the component template APIs
Part of #404 
> Add support for component template APIs

- CHANGELOG.md
- tests/Tests.Core/Tests.Core.csproj
Backport 35a0fd8f3b9fd5b0f82473cde2c3e8e1b252e89b from #431 
> [Backport 1.x] Bump Microsoft.TestPlatform.ObjectModel from 17.7.2 to 17.8.0 (#431)

- guides/json.md
Remove duplicated paragraph from json.md guide
> Remove duplicated paragraph from json.md guide

- src/OpenSearch.Client/_Generated/Descriptors.Cluster.cs
- src/OpenSearch.Client/_Generated/Descriptors.DanglingIndices.cs
- src/OpenSearch.Client/_Generated/Descriptors.Ingest.cs
- src/OpenSearch.Client/_Generated/Descriptors.NoNamespace.cs
- src/OpenSearch.Client/_Generated/Descriptors.Nodes.cs
- src/OpenSearch.Client/_Generated/Descriptors.Snapshot.cs
- src/OpenSearch.Client/_Generated/Descriptors.Tasks.cs
- src/OpenSearch.Client/_Generated/IOpenSearchClient.cs
- src/OpenSearch.Client/_Generated/Requests.Cluster.cs
- src/OpenSearch.Client/_Generated/Requests.DanglingIndices.cs
- src/OpenSearch.Client/_Generated/Requests.Ingest.cs
- src/OpenSearch.Client/_Generated/Requests.NoNamespace.cs
- src/OpenSearch.Client/_Generated/Requests.Nodes.cs
- src/OpenSearch.Client/_Generated/Requests.Snapshot.cs
- src/OpenSearch.Client/_Generated/Requests.Tasks.cs
- src/OpenSearch.Client/_Generated/Requests.cs
- src/OpenSearch.Net/_Generated/Api/Enums.cs
- src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Cluster.cs
- src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.DanglingIndices.cs
- src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Ingest.cs
- src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.NoNamespace.cs
- src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Nodes.cs
- src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Snapshot.cs
- src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Tasks.cs
> Sort usings in generated code

- CHANGELOG.md
- abstractions/src/OpenSearch.OpenSearch.Xunit/OpenSearch.OpenSearch.Xunit.csproj
- tests/Tests.Core/Tests.Core.csproj
Backport e8919eff60f5235a68af74733603f7bee246a2e5 from #441 
> [Backport 1.x] Bump xunit from 2.6.1 to 2.6.2 (#441)

- src/OpenSearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
- src/OpenSearch.Net/OpenSearchLowLevelClient.Indices.cs
Cleanup old IndexTemplateV2 methods that have been replaced and missed removal in #437 
> Cleanup old IndexTemplateV2 methods that have been replaced

- CHANGELOG.md
- src/OpenSearch.Net/Api/RequestParameters/RequestParameters.Cluster.cs
- src/OpenSearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
- src/OpenSearch.Net/OpenSearchLowLevelClient.Cluster.cs
- src/OpenSearch.Net/OpenSearchLowLevelClient.Indices.cs
Re-adds and deprecates some of the low-level operations that were removed in #411 & #437  to avoid breaking changes in 1.x. 
> [Backport 1.x] Re-add and deprecate replaced operations to avoid breaking changes

- .github/bump-version.sh
- .github/workflows/bump-version.yml
- .github/workflows/release.yml
Automates the version bump workflow so that it will create PRs into the relevant version branches when a new version tag is pushed. As well as creating the `{major}.x` and/or `{major}.{minor}` branches when a `v{major}.0.0` or `v{major}.{minor}.0` tag is pushed.
Additionally removes one of the hardcoded versions out of a workflow and has it read from elsewhere, so that version bump workflow doesn't need "modify workflow" permission to bump the version.
> Automate the version bump workflow

- CHANGELOG.md
Updates the CHANGELOG in `main` following the 1.6.0 release
> Update CHANGELOG post 1.6.0 release

- CHANGELOG.md
- abstractions/src/OpenSearch.OpenSearch.Xunit/OpenSearch.OpenSearch.Xunit.csproj
- abstractions/tests/OpenSearch.OpenSearch.EphemeralTests/OpenSearch.OpenSearch.EphemeralTests.csproj
- abstractions/tests/OpenSearch.Stack.ArtifactsApiTests/OpenSearch.Stack.ArtifactsApiTests.csproj
- src/ApiGenerator/ApiGenerator.csproj
- tests/Tests.Auth.AwsSigV4/Tests.Auth.AwsSigV4.csproj
- tests/Tests.Core/Tests.Core.csproj
- tests/Tests.Reproduce/Tests.Reproduce.csproj
- tests/Tests.ScratchPad/Tests.ScratchPad.csproj
- tests/Tests/Tests.csproj
Backports recent dependabot PRs to 1.x
> [Backport 1.x] Bump BenchMarkDotNet, xunit, xunit.runner.visualstudio & CSharpier.Core

- CHANGELOG.md
- abstractions/tests/OpenSearch.OpenSearch.EphemeralTests/OpenSearch.OpenSearch.EphemeralTests.csproj
- abstractions/tests/OpenSearch.Stack.ArtifactsApiTests/OpenSearch.Stack.ArtifactsApiTests.csproj
- tests/Tests.Auth.AwsSigV4/Tests.Auth.AwsSigV4.csproj
- tests/Tests.Reproduce/Tests.Reproduce.csproj
- tests/Tests/Tests.csproj
Backports f97e43317768be97d159980f306bac96874d9cfc from #486 
> [Backport 1.x] Bump xunit.runner.visualstudio from 2.5.5 to 2.5.6 (#486)

- CHANGELOG.md
- abstractions/src/OpenSearch.OpenSearch.Ephemeral/OpenSearch.OpenSearch.Ephemeral.csproj
Backports 74d542be829a598b4e8c7dab947a453f36fc0bf8 from #494 
> [Backport 1.x] Bump JetBrains.Annotations from 2023.2.0 to 2023.3.0 (#494)

- CHANGELOG.md
- abstractions/tests/OpenSearch.OpenSearch.EphemeralTests/OpenSearch.OpenSearch.EphemeralTests.csproj
- abstractions/tests/OpenSearch.Stack.ArtifactsApiTests/OpenSearch.Stack.ArtifactsApiTests.csproj
- tests/Tests.Auth.AwsSigV4/Tests.Auth.AwsSigV4.csproj
- tests/Tests.Reproduce/Tests.Reproduce.csproj
- tests/Tests/Tests.csproj
Backports 6ac8f9aaa142a76b95fbffeca1a238ba89049fc4 from #496 
> [Backport 1.x] Bump Microsoft.NET.Test.Sdk from 17.7.2 to 17.8.0 (#496)

- CHANGELOG.md
- src/OpenSearch.Net/Connection/HttpConnection.cs
- tests/Tests.Auth.AwsSigV4/AwsSigV4HttpConnectionTests.cs
- tests/Tests.Auth.AwsSigV4/Utils/TestableAwsSigV4HttpConnection.cs
- tests/Tests.Core/Connection/Http/HttpRequestMessageAssertions.cs
- tests/Tests.Core/Connection/Http/MockHttpMessageHandler.cs
- tests/Tests/Connection/Http/HttpConnectionTests.cs
- tests/Tests/Connection/Http/MockableHttpConnection.cs
Add support for `PATCH` in `HttpConnection.ConvertHttpMethod`.
Fixes #488 
> Add support for `PATCH` in `HttpConnection.ConvertHttpMethod`

- CHANGELOG.md
- tests/Tests.Domain/Tests.Domain.csproj
Backport 4e38cb60c5492b36d1c5e492d3fde357b9ac83d5 from #495
> [Backport 1.x] Bump Bogus from 34.0.2 to 35.3.0 (#495)

- CHANGELOG.md
- src/OpenSearch.Client/Mapping/Visitor/PropertyWalker.cs
- tests/Tests/Mapping/PropertyWalkerTests.cs
> Fix for #380.

- CHANGELOG.md
- src/OpenSearch.Net/Connection/HttpConnection.cs
- tests/Tests.Auth.AwsSigV4/AwsSigV4HttpConnectionTests.cs
- tests/Tests.Auth.AwsSigV4/Utils/TestableAwsSigV4HttpConnection.cs
- tests/Tests.Core/Connection/Http/HttpRequestMessageAssertions.cs
- tests/Tests.Core/Connection/Http/MockHttpMessageHandler.cs
- tests/Tests/Connection/Http/HttpConnectionTests.cs
- tests/Tests/Connection/Http/MockableHttpConnection.cs
Backports 4e721ee854f90fb66f05002c991492c081b68bf0 from #489 
> [Backport 1.x] Add support for `PATCH` in `HttpConnection.ConvertHttpMethod` (#489)

- CHANGELOG.md
- src/OpenSearch.Client/Mapping/Visitor/PropertyWalker.cs
- tests/Tests/Mapping/PropertyWalkerTests.cs
Signed-off-by: Kostas <ghost0002001@hotmail.com>
(cherry picked from commit 14c8af658c00f3aa94f4a067df2e828ebb609d21)
Fix for https://github.com/opensearch-project/opensearch-net/issues/380.
https://github.com/opensearch-project/opensearch-net/issues/380.
> Fix for `IEnumerable<int?>` property mapping ( #380 )

- CHANGELOG.md
Corrects duplicated changelog header
> Correct duplicated changelog header

- CHANGELOG.md
- abstractions/src/OpenSearch.OpenSearch.Xunit/OpenSearch.OpenSearch.Xunit.csproj
- tests/Tests.Core/Tests.Core.csproj
Backports f554b8d980e3a284926fd8414484b2d477220874 from #492 
> [Backport 1.x] Bump xunit from 2.6.3 to 2.6.5 (#492)

- CHANGELOG.md
- src/ApiGenerator/ApiGenerator.csproj
Backports a63e4d84aa101ffffa97ffcdcc54df935be475dd from #530 
> [Backport 1.x] Bump NSwag.Core.Yaml from 13.20.0 to 14.0.2 (#530)

- CHANGELOG.md
- src/ApiGenerator/ApiGenerator.csproj
Backports 47eecef24f663aa597d94d9ca8d0cc5f5c35ad8e from #541 
> [Backport 1.x] Bump NSwag.Core.Yaml from 14.0.2 to 14.0.3 (#541)

- CHANGELOG.md
- src/OpenSearch.Net/Configuration/ConnectionConfiguration.cs
Use DefaultMemoryStreamFactory static property for the default in ConnectionConfiguration - currently the private member is initialized to a different value, which is confusing.
Resolves #551 
> Actually use ConnectionConfiguration.DefaultMemoryStreamFactory

- CHANGELOG.md
- src/ApiGenerator/ApiGenerator.csproj
Backport 2d4e632f98d8ccfc4fd2b904804abafd0508a80e from #556 
> [Backport 1.x] Bump CSharpier.Core from 0.27.2 to 0.27.3 (#556)

- CHANGELOG.md
- src/OpenSearch.Net/Configuration/ConnectionConfiguration.cs
Backport 80854014b7376f6882ebb3010c0309a0f9774808 from #552
> [Backport 1.x] Actually use ConnectionConfiguration.DefaultMemoryStreamFactory (#552)

- CHANGELOG.md
- abstractions/src/OpenSearch.Stack.ArtifactsApi/OpenSearch.Stack.ArtifactsApi.csproj
Backport daae8d1bc0179694e6cdd65eb57d77b6dd8445c9 from #575 
> [Backport 1.x] Bump System.Text.Json from 8.0.2 to 8.0.3 (#575)

- CHANGELOG.md
- src/OpenSearch.Client/Snapshot/Repositories/S3Repository.cs
- tests/Tests.Reproduce/GitHubIssue573.cs
Fixes deserialization of S3 snapshot repository without settings
Fixes #573 
> Fix deserialization of S3 snapshot repository without settings

- samples/Samples/NeuralSearch/NeuralSearchSample.cs
- samples/Samples/Sample.cs
Adds a working neural search sample. Many of the APIs and typings do not yet exist in the client. Will add a proper guide and update the sample in a future PR which implements at least the `neural` query type and `text_embedding` ingest pipeline processor type.
Relates to #613 & #372
> Add a working neural search sample

- .github/workflows/integration.yml
Building the k-NN plugin (specifically one of its submodule dependencies) requires the git user to be configured.
> Fix k-NN plugin build

- CHANGELOG.md
- src/OpenSearch.Client/QueryDsl/Specialized/ScriptScore/ScriptScoreQuery.cs
- tests/Tests/QueryDsl/Specialized/ScriptScore/ScriptScoreQueryUsageTests.cs
Add support for `min_score` property in `ScriptScoreQuery`. This also is a proper version of https://github.com/opensearch-project/opensearch-net/pull/623 which I closed after realising trying to add something to an SDK in the github browser editor was probably a bad idea.
Also, when running `build.bat` locally I get a few errors, I don't want to take the action minutes up with another duff run, so could someone check if this is just something not correctly set up on my machine, or an actual error I've caused?
I could be missing it, but I couldn't find a guide on how to run these tests so I'm assuming I'm missing some setup
Closes #622 
For more information on following …
> feat: add support for min_score on ScriptScoreQuery

- CHANGELOG.md
- src/ApiGenerator/ApiGenerator.csproj
Backport f6f62096a1593f36e8889c53a03ed3e4e4940455 from #640
> Bump Spectre.Console from 0.48.0 to 0.49.1 (#640)

- CHANGELOG.md
- UPGRADING.md
- src/ApiGenerator/Views/HighLevel/Client/FluentSyntax/FluentInterfaceMethod.cshtml
- src/ApiGenerator/Views/HighLevel/Client/Implementation/MethodInterface.cshtml
- src/ApiGenerator/Views/HighLevel/Client/Implementation/OpenSearchClient.Http.cshtml
- src/ApiGenerator/Views/HighLevel/Client/Implementation/OpenSearchClient.Namespace.cshtml
- src/ApiGenerator/Views/HighLevel/Client/Implementation/OpenSearchClient.cshtml
- src/ApiGenerator/Views/HighLevel/Client/InitializerSyntax/InitializerInterfaceMethod.cshtml
- src/ApiGenerator/Views/HighLevel/Client/Interface/IOpenSearchClient.cshtml
- src/OpenSearch.Client/OpenSearchClient.Indices.cs
- src/OpenSearch.Client/_Generated/IOpenSearchClient.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.Cat.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.Cluster.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.DanglingIndices.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.Http.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.Indices.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.Ingest.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.Nodes.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.Snapshot.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.Tasks.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.cs
Say you created a method using IOpenSearchClient:
```
public void CreateIndex(IOpenSearchClient client, string name) {
client.Indices.Create(name);
}
```
Then you want to write a unit test for it. Since you don't want unit tests to depend on external services, you would likely mock out the IOpenSearchClient.  So, you might write:
```
public void CreateIndex_Always_CreatesAnIndex() {
// arrange
var clientMock = new Moq.Mock<IOpenSearchClient>();
clientMock.Setup(i => i.Indices.Create(name, null));
var name = "Name";
// act
_instance.CreateIndex(client, name)
// assert
clientMock.Verify(i => i.Indices.Create(name, null), Times.Once);
}
```
But this doesn't work. IOpenSearchClient is an interface and can be mocked, but IOpenSearchClient.Indices is IndicesNamespace, a concrete class, and …
> Add interfaces to OpenSearchClient's namespaces API specifications (fixes #423)

- DEVELOPER_GUIDE.md
- README.md
Added a brief developer guide, much in the same form as the python repository. The client code generation part is a stub for now, as I am not sure how that works right now. Please let me know what to put there.
Couldn't find any issues for this other than a very old closed one from years ago.
> Add developer guide

- .github/workflows/code-gen.yml
Ensure generated code is up-to-date on PRs.
Doesn't pull new versions of spec, merely ensures changes to generator have been captured or manual changes haven't been made to generated code.
Part of #667 
> Ensure generated code is up-to-date on PRs

- .github/actions/start-opensearch/action.yml
- .github/workflows/integration-yaml-tests.yml
Fix building of OpenSearch 3.0.0-SNAPSHOT/main for unreleased YAML tests by installing JDK 21. Also hard code "secure" password in start script, as attempt at random generation occasionally failed password requirements or /dev/urandom having no data.
> Fix building of OpenSearch 3.0.0-SNAPSHOT/main by installing JDK 21

- CHANGELOG.md
- abstractions/src/OpenSearch.Stack.ArtifactsApi/OpenSearch.Stack.ArtifactsApi.csproj
Backports e76175c44204fe67160b12b0ddb7e43c86f01530 from #702 
> [Backport 1.x] Bump System.Text.Json from 8.0.3 to 8.0.4 in /abstractions/src/OpenSearch.Stack.ArtifactsApi (#702)

- tests/Tests.YamlRunner/SkipList.fs
Backport #719 via 1db3d60e6073e4d5e05def4b2e2c6beb70aafd17
> [Backport 1.x] Skip failing indices.put_alias YAML tests (#719)

- src/OpenSearch.Client/OpenSearchClient.Indices.cs
Update `Indices.BulkAsync` summary with the correct API name
Closes [#715].
> Fix Indices.BulkAsync summary

- .github/workflows/bump-version.yml
- .github/workflows/integration-yaml-tests.yml
- .github/workflows/integration.yml
- .github/workflows/test-jobs.yml
Follow [best practices](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable) for interpolating in inline scripts in GitHub Actions by using intermediate env vars. 
> Use intermediate env var instead of interpolating directly in inline shell scripts

- CHANGELOG.md
- src/ApiGenerator/ApiGenerator.csproj
- src/OpenSearch.Net/_Generated/Api/Enums.cs
Backport #760 via e352e0b4573356e38bf6f174d7a025285b026389
> [Backport 1.x] Bump CSharpier.Core and System.Text.Json (#760)

- .github/workflows/integration.yml
- CHANGELOG.md
- abstractions/src/OpenSearch.OpenSearch.Ephemeral/EphemeralClusterConfiguration.cs
- abstractions/src/OpenSearch.OpenSearch.Ephemeral/Tasks/InstallationTasks/InstallPlugins.cs
- abstractions/src/OpenSearch.OpenSearch.Xunit/XunitPlumbing/IntegrationTestDiscoverer.cs
- abstractions/src/OpenSearch.OpenSearch.Xunit/XunitPlumbing/SkipPrereleaseVersionsAttribute.cs
- abstractions/src/OpenSearch.OpenSearch.Xunit/XunitPlumbing/SkipVersionAttribute.cs
- abstractions/src/OpenSearch.Stack.ArtifactsApi/Products/OpenSearchPlugin.cs
- samples/Samples/NeuralSearch/NeuralSearchSample.cs
- samples/Samples/Sample.cs
- src/OpenSearch.Client/CommonAbstractions/Infer/Indices/Indices.cs
- src/OpenSearch.Client/Ingest/ProcessorFormatter.cs
- src/OpenSearch.Client/Ingest/Processors/Plugins/NeuralSearch/InferenceProcessorBase.cs
- src/OpenSearch.Client/Ingest/Processors/Plugins/NeuralSearch/TextEmbeddingProcessor.cs
- src/OpenSearch.Client/Ingest/ProcessorsDescriptor.cs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/IQueryContainer.cs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
- src/OpenSearch.Client/QueryDsl/Query.cs
- src/OpenSearch.Client/QueryDsl/Specialized/Neural/NeuralQuery.cs
- src/OpenSearch.Client/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
- src/OpenSearch.Client/QueryDsl/Visitor/QueryVisitor.cs
- src/OpenSearch.Client/QueryDsl/Visitor/QueryWalker.cs
- tests/Tests.Core/ManagedOpenSearch/Clusters/WritableCluster.cs
- tests/Tests/Ingest/ProcessorAssertions.cs
- tests/Tests/Ingest/PutPipeline/PutPipelineApiTests.cs
- tests/Tests/QueryDsl/QueryDslUsageTestsBase.cs
- tests/Tests/QueryDsl/Specialized/Knn/KnnQueryUsageTests.cs
- tests/Tests/QueryDsl/Specialized/Neural/NeuralQueryUsageTests.cs
Adds support for the `neural` query type and the `text_embedding` ingest processor type
> Support the `neural` query type and `text_embedding` ingest processor type

- CHANGELOG.md
- src/ApiGenerator/ApiGenerator.csproj
Backport #767 via 8aa8e7797bfab66893dacb4ce3a4c0bdc88cdc70
> [Backport 1.x] Bump CSharpier.Core from 0.29.0 to 0.29.1 (#767)

- OpenSearch.sln.DotSettings
- src/ApiGenerator/Domain/Specification/Deprecation.cs
- src/ApiGenerator/Generator/ApiEndpointFactory.cs
- src/ApiGenerator/opensearch-openapi.yaml
Backport #782 via 3b526f7a4624ade192bc16d40742a5d968f7e8e6
> [Backport 1.x] Fix time type matching and normalize all deprecation versions (#782)

- jenkins/release.jenkinsFile
Update Jenkins release docker image
> Update Jenkins release docker image

- src/ApiGenerator/Configuration/Overrides/Endpoints/DeleteByQueryOverrides.cs
- src/ApiGenerator/Configuration/Overrides/Endpoints/ReindexOnServerOverrides.cs
- src/ApiGenerator/Configuration/Overrides/Endpoints/SearchOverrides.cs
- src/ApiGenerator/Configuration/Overrides/Endpoints/UpdateByQueryOverrides.cs
- src/ApiGenerator/Domain/Code/HttpMethod.cs
- src/ApiGenerator/Domain/Specification/ApiEndpoint.cs
- src/ApiGenerator/Domain/Specification/UrlPart.cs
- src/ApiGenerator/Generator/ApiEndpointFactory.cs
- src/ApiGenerator/Views/LowLevel/Client/Interface/IOpenSearchLowLevelClient.cshtml
- src/ApiGenerator/opensearch-openapi.yaml
- src/OpenSearch.Net/Api/Enums.cs
- src/OpenSearch.Net/OpenSearch.Net.csproj
- src/OpenSearch.Net/_Generated/Api/Enums.cs
- tests/Tests.YamlRunner/DoMapper.fs
- tests/Tests.YamlRunner/SkipList.fs
> [Backport 1.x] Re-generate the root namespace (#804)

- .github/actions/run-released-opensearch/action.yml
- .github/actions/start-opensearch/action.yml
- .github/workflows/integration-yaml-tests.yml
- src/ApiGenerator/Domain/Code/CsharpNames.cs
- src/ApiGenerator/Generator/ApiEndpointFactory.cs
- src/ApiGenerator/Views/HighLevel/Requests/PlainRequestBase.cshtml
- src/OpenSearch.Client/_Generated/Requests.cs
> [Backport 1.x] Better handle multi-type schemas

- CHANGELOG.md
- src/ApiGenerator/ApiGenerator.csproj
Bumps `Microsoft.Extensions.Caching.Memory` from 6.0.0 to 8.0.1, to resolve a CVE
This only affects the code generator, so is not relevant to users of the library.
Fixes #843 
> Bump `Microsoft.Extensions.Caching.Memory` from 6.0.0 to 8.0.1

- CHANGELOG.md
- abstractions/src/OpenSearch.OpenSearch.Xunit/OpenSearch.OpenSearch.Xunit.csproj
- src/ApiGenerator/ApiGenerator.csproj
- src/OpenSearch.Client/_Generated/ApiUrlsLookup.cs
- src/OpenSearch.Net.Auth.AwsSigV4/OpenSearch.Net.Auth.AwsSigV4.csproj
- src/OpenSearch.Net/OpenSearch.Net.csproj
- tests/Tests.Core/Tests.Core.csproj
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
Backporting dependabot updates to 1.x
> [Backport 1.x] Dependabot updates
