- .github/workflows/integration.yml
- README.md
- build/scripts/ReleaseNotes.fs
- build/scripts/XmlDocPatcher.fs
This PR adds status badges to README.md file for compile, unit test, and integration test workflows.
It also includes minor syntax improvements for build/scripts project and integration workflows.
> Add status badges to the README file 

- .github/workflows/compile.yml
- .github/workflows/integration.yml
- .github/workflows/release.yml
- .github/workflows/test-jobs.yml
- global.json
Signed-off-by: MaxKsyunz <maxk@bitquilltech.com>
backport #53 
_List any issues this PR will resolve, e.g. Closes [...]._ 
> [1.x] Update dotnet version to 5.0.405 (#53)

- USER_GUIDE.md
> Fixed user guide

- build/scripts/packages.lock.json
- build/scripts/scripts.fsproj
- src/ApiGenerator/ApiGenerator.csproj
- src/ApiGenerator/packages.lock.json
- src/OpenSearch.Client.JsonNetSerializer/OpenSearch.Client.JsonNetSerializer.csproj
- src/OpenSearch.Client.JsonNetSerializer/packages.lock.json
- tests/Tests.ClusterLauncher/packages.lock.json
- tests/Tests.Core/packages.lock.json
- tests/Tests.Domain/Tests.Domain.csproj
- tests/Tests.Domain/packages.lock.json
- tests/Tests.Reproduce/packages.lock.json
- tests/Tests.ScratchPad/packages.lock.json
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
- tests/Tests.YamlRunner/packages.lock.json
- tests/Tests/Tests.csproj
- tests/Tests/packages.lock.json
Update `Newtonsoft.Json` from 12.0.1 to 13.0.1.
Signed-off-by: Yury Fridlyand <yuryf@bitquilltech.com>
Combines all dependabot PRs into single one.
Closes:
https://github.com/opensearch-project/opensearch-net/pull/57
https://github.com/opensearch-project/opensearch-net/pull/58
https://github.com/opensearch-project/opensearch-net/pull/59
https://github.com/opensearch-project/opensearch-net/pull/60
https://github.com/opensearch-project/opensearch-net/pull/61
https://github.com/opensearch-project/opensearch-net/pull/62
For more information on following Developer Certificate of Origin and signing off your commits, please check …
> Follow dependabot recommendation

- README.md
> Documentation link update

- .github/dependabot.yml
- .github/workflows/links.yml
- CONTRIBUTING.md
* Adding linkchecker workflow.
* Adding Dependabot config file to auto-update dependencies. Opens PRs on my fork: https://github.com/VachaShah/opensearch-net/pulls
_List any issues this PR will resolve, e.g. Closes [...]._ 
> Adding linkchecker and dependabot

- .github/workflows/changelog_verifier.yml
- .github/workflows/dependabot_changelog.yml
- CHANGELOG.md
Signed-off-by: Theo Truong <theotr@amazon.com>
> Added dependabot_changelog workflow to update changelog for dependabot

- CHANGELOG.md
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
- tests/Tests.YamlRunner/TestsDownloader.fs
- tests/Tests.YamlRunner/packages.lock.json
- tests/Tests/Tests.csproj
- tests/Tests/packages.lock.json
Update the FSharp.Core and FSharp.Data dependencies
> Update the FSharp.Core and FSharp.Data dependencies

- CHANGELOG.md
- build/scripts/packages.lock.json
- build/scripts/scripts.fsproj
Update the Fake.* dependencies
> Update the Fake.* dependencies

- src/ApiGenerator/ApiGenerator.csproj
- src/ApiGenerator/Program.cs
- src/ApiGenerator/packages.lock.json
Updates the Spectre.Console dependency of the ApiGenerator
> Bump Spectre.Console from 0.30.0 to 0.47.0

- CHANGELOG.md
- abstractions/src/OpenSearch.OpenSearch.Managed/OpenSearchNode.cs
- src/OpenSearch.Client/Mapping/DynamicTemplate/SingleMapping.cs
- src/OpenSearch.Client/Mapping/Types/FieldType.cs
- src/OpenSearch.Client/Mapping/Types/Properties.cs
- src/OpenSearch.Client/Mapping/Types/PropertyFormatter.cs
- src/OpenSearch.Client/Mapping/Types/Specialized/Knn/KnnVectorProperty.cs
- src/OpenSearch.Client/Mapping/Visitor/IPropertyVisitor.cs
- src/OpenSearch.Client/Mapping/Visitor/NoopPropertyVisitor.cs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/IQueryContainer.cs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
- src/OpenSearch.Client/QueryDsl/Query.cs
- src/OpenSearch.Client/QueryDsl/Specialized/Knn/KnnQuery.cs
- src/OpenSearch.Client/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
- src/OpenSearch.Client/QueryDsl/Visitor/QueryVisitor.cs
- src/OpenSearch.Client/QueryDsl/Visitor/QueryWalker.cs
- tests/Tests.Core/ManagedOpenSearch/NodeSeeders/DefaultSeeder.cs
- tests/Tests.Domain/Project.cs
- tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
- tests/Tests/Mapping/Types/Specialized/Knn/KnnVectorPropertyTests.cs
- tests/Tests/QueryDsl/Specialized/Knn/KnnQueryUsageTests.cs
Implements bindings for k-NN approximate search as well as index property mappings.
Fixes #178 
> Implement k-NN approximate search and mappings bindings

- CHANGELOG.md
- abstractions/src/OpenSearch.OpenSearch.Managed/OpenSearchNode.cs
- src/OpenSearch.Client/Mapping/DynamicTemplate/SingleMapping.cs
- src/OpenSearch.Client/Mapping/Types/FieldType.cs
- src/OpenSearch.Client/Mapping/Types/Properties.cs
- src/OpenSearch.Client/Mapping/Types/PropertyFormatter.cs
- src/OpenSearch.Client/Mapping/Types/Specialized/Knn/KnnVectorProperty.cs
- src/OpenSearch.Client/Mapping/Visitor/IPropertyVisitor.cs
- src/OpenSearch.Client/Mapping/Visitor/NoopPropertyVisitor.cs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/IQueryContainer.cs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
- src/OpenSearch.Client/QueryDsl/Query.cs
- src/OpenSearch.Client/QueryDsl/Specialized/Knn/KnnQuery.cs
- src/OpenSearch.Client/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
- src/OpenSearch.Client/QueryDsl/Visitor/QueryVisitor.cs
- src/OpenSearch.Client/QueryDsl/Visitor/QueryWalker.cs
- tests/Tests.Core/ManagedOpenSearch/NodeSeeders/DefaultSeeder.cs
- tests/Tests.Domain/Project.cs
- tests/Tests/Indices/MappingManagement/PutMapping/PutMappingApiTest.cs
- tests/Tests/Mapping/Types/Specialized/Knn/KnnVectorPropertyTests.cs
- tests/Tests/QueryDsl/Specialized/Knn/KnnQueryUsageTests.cs
Backport 38330056f3a9e056a98f71e7f3e78dc81d5dc614 from #215
> [Backport 1.x] Implement k-NN approximate search and mappings bindings

- CHANGELOG.md
- src/OpenSearch.Client.JsonNetSerializer/packages.lock.json
- src/OpenSearch.Client/packages.lock.json
- src/OpenSearch.Net.Auth.AwsSigV4/packages.lock.json
- src/OpenSearch.Net.VirtualizedCluster/packages.lock.json
- src/OpenSearch.Net/packages.lock.json
- src/_PublishArtifacts.Build.props
Backport 5740ca9b889cbd906964ec98dac66d18ccdce849 from #235
> [Backport 1.x] Bump Microsoft.SourceLink.GitHub from 1.0.0 to 1.1.1

- CHANGELOG.md
- abstractions/tests/OpenSearch.OpenSearch.EphemeralTests/packages.lock.json
- abstractions/tests/OpenSearch.Stack.ArtifactsApiTests/packages.lock.json
- src/OpenSearch.Client.JsonNetSerializer/packages.lock.json
- src/OpenSearch.Client/packages.lock.json
- src/OpenSearch.Net.Auth.AwsSigV4/packages.lock.json
- src/OpenSearch.Net.VirtualizedCluster/packages.lock.json
- src/OpenSearch.Net/OpenSearch.Net.csproj
- src/OpenSearch.Net/packages.lock.json
- tests/Tests.Auth.AwsSigV4/packages.lock.json
- tests/Tests.ClusterLauncher/packages.lock.json
- tests/Tests.Core/packages.lock.json
- tests/Tests.Domain/packages.lock.json
- tests/Tests.Reproduce/packages.lock.json
- tests/Tests.ScratchPad/packages.lock.json
- tests/Tests.YamlRunner/packages.lock.json
- tests/Tests/packages.lock.json
Backport 8386cbed95ee5319df1f375edfa355cd1a2d6f5a from #217
> [Backport 1.x] Bump Microsoft.CSharp from 4.6.0 to 4.7.0

- CHANGELOG.md
- abstractions/tests/OpenSearch.OpenSearch.EphemeralTests/packages.lock.json
- abstractions/tests/OpenSearch.Stack.ArtifactsApiTests/packages.lock.json
- src/OpenSearch.Client.JsonNetSerializer/packages.lock.json
- src/OpenSearch.Client/packages.lock.json
- src/OpenSearch.Net.Auth.AwsSigV4/packages.lock.json
- src/OpenSearch.Net.VirtualizedCluster/packages.lock.json
- src/OpenSearch.Net/OpenSearch.Net.csproj
- src/OpenSearch.Net/packages.lock.json
- tests/Tests.Auth.AwsSigV4/packages.lock.json
- tests/Tests.ClusterLauncher/packages.lock.json
- tests/Tests.Core/packages.lock.json
- tests/Tests.Domain/packages.lock.json
- tests/Tests.Reproduce/packages.lock.json
- tests/Tests.ScratchPad/Tests.ScratchPad.csproj
- tests/Tests.ScratchPad/packages.lock.json
- tests/Tests.YamlRunner/packages.lock.json
- tests/Tests/packages.lock.json
Backport f86fbd5ef15fc80f8e5afdc46a0c38d13ce2eae3 from #245
> [Backport 1.x] Bump System.Diagnostics.DiagnosticSource from 6.0.0 to 6.0.1 

- CHANGELOG.md
- tests/Tests/Tests.csproj
- tests/Tests/packages.lock.json
Backport 24991154dfa12dc88934233fed929d077eb6eb68 from #244
> [Backport 1.x] Bump System.Reactive from 5.0.0 to 6.0.0

- CHANGELOG.md
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
- tests/Tests.YamlRunner/packages.lock.json
Backport e13396dc28d11a644c2d8be98344bd4d46b52729 from #214
> [Backport 1.x] Bump FSharp.Data from 5.0.2 to 6.2.0

- CHANGELOG.md
- abstractions/src/OpenSearch.OpenSearch.Ephemeral/packages.lock.json
- abstractions/src/OpenSearch.OpenSearch.Managed/OpenSearch.OpenSearch.Managed.csproj
- abstractions/src/OpenSearch.OpenSearch.Managed/packages.lock.json
- abstractions/src/OpenSearch.OpenSearch.Xunit/packages.lock.json
- abstractions/tests/OpenSearch.OpenSearch.EphemeralTests/packages.lock.json
- abstractions/tests/OpenSearch.Stack.ArtifactsApiTests/packages.lock.json
- build/scripts/packages.lock.json
- build/scripts/scripts.fsproj
- tests/Tests.Auth.AwsSigV4/packages.lock.json
- tests/Tests.ClusterLauncher/packages.lock.json
- tests/Tests.Configuration/packages.lock.json
- tests/Tests.Core/Tests.Core.csproj
- tests/Tests.Core/packages.lock.json
- tests/Tests.Domain/packages.lock.json
- tests/Tests.Reproduce/packages.lock.json
- tests/Tests.ScratchPad/packages.lock.json
- tests/Tests/packages.lock.json
Backport 2caa7e6447ccf6c667fe19c434a4817d0502fb37 from #236
> [Backport 1.x] Bump Proc from 0.6.1 to 0.6.2

- CHANGELOG.md
- build/scripts/packages.lock.json
- build/scripts/scripts.fsproj
Backport aa7b1c3f44237a7e653206c8cb2a2b97de0f5f5a from #230
> [Backport 1.x] Bump Fake.IO.FileSystem from 5.23.1 to 6.0.0

- .github/bump-version.sh
There's just so many wonderful flavours of `sed` 🙃 
> Fix bump-version script for GNU sed

- .github/workflows/bump-version.yml
Update packages.lock.json on version bump and add skip-changelog label
> Add skip-changelog label to version bump PRs

- CHANGELOG.md
Clean up the CHANGELOG after the 1.4.0 release
> Tidy CHANGELOG post 1.4.0 release

- CHANGELOG.md
Fixes the compare links on the 1.x CHANGELOG
> Fix compare links in 1.x CHANGELOG

- CHANGELOG.md
- build/scripts/Targets.fs
- build/scripts/scripts.fsproj
Backport 44f60ec33d9c1974d159b664a693bba0831dc5c8 from #291
> [Backport 1.x] Bump Bullseye from 3.3.0 to 4.2.1 (#291)

- CHANGELOG.md
Prepare CHANGELOG.md for v1.5.0 release
> Prepare CHANGELOG.md for v1.5.0 release

- CHANGELOG.md
- src/OpenSearch.Net.Auth.AwsSigV4/OpenSearch.Net.Auth.AwsSigV4.csproj
- tests/Tests.ScratchPad/Tests.ScratchPad.csproj
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
Backport most-recent dependabot PRs #357 #358 #359 to 1.x
> [Backport 1.x] Upgrade FSharp.Data, BenchMarkDotNet & AWSSDK.Core

- CHANGELOG.md
- src/_PublishArtifacts.Build.props
Backport 85451de24873d24f7706ff95e9d8a4253998c235 from #449 
> [Backport 1.x] Bump Microsoft.SourceLink.GitHub from 1.1.1 to 8.0.0 (#449)

- CHANGELOG.md
Prepares the CHANGELOG section for releasing `v1.6.0`
> Prepare CHANGELOG for 1.6.0 release

- .github/workflows/release.yml
- build/scripts/Commandline.fs
- build/scripts/ReleaseNotes.fs
Fix GitHub rate limit errors in Create Release Candidate workflow
Fixes #139
> Fix GitHub rate limit errors in Create Release Candidate workflow

- CHANGELOG.md
- abstractions/src/OpenSearch.OpenSearch.Xunit/OpenSearch.OpenSearch.Xunit.csproj
- tests/Tests.Core/Tests.Core.csproj
- tests/Tests.YamlRunner/Tests.YamlRunner.fsproj
Backports updating the Argu and xunit packages.
> [Backport 1.x] Update Argu & xunit

- CHANGELOG.md
- src/ApiGenerator/ApiGenerator.csproj
- tests/Tests.ScratchPad/Tests.ScratchPad.csproj
> [Backport 1.x] Bump BenchMarkDotNet & CSharpier.Core

- CHANGELOG.md
- abstractions/tests/OpenSearch.OpenSearch.EphemeralTests/OpenSearch.OpenSearch.EphemeralTests.csproj
- abstractions/tests/OpenSearch.Stack.ArtifactsApiTests/OpenSearch.Stack.ArtifactsApiTests.csproj
- tests/Tests.Core/Tests.Core.csproj
- tests/Tests.Reproduce/Tests.Reproduce.csproj
Backports 39da13eb31ef12ffe97348eaf0e8029c967e5263 from #540 
> [Backport 1.x] Bump Microsoft.NET.Test.Sdk and Microsoft.TestPlatform.ObjectModel (#540)

- CHANGELOG.md
Prepare 1.7.0 changelog for release
> [1.x] Prepare 1.7.0 changelog for release

- CHANGELOG.md
Prepare 1.7.0 changelog for release
> [main] Prepare 1.7.0 changelog for release

- CHANGELOG.md
- abstractions/src/OpenSearch.Stack.ArtifactsApi/OpenSearch.Stack.ArtifactsApi.csproj
Backport 75c2f0adecd3d7e3860358229d9b925aeda0f3c4 from #570 
> [Backport 1.x] Bump System.Text.Json from 8.0.1 to 8.0.2 (#570)

- CHANGELOG.md
- src/OpenSearch.Client/Modules/SnapshotAndRestore/Repositories/S3Repository.cs
- tests/Tests.Reproduce/GitHubIssue573.cs
Backports df942ab3d545cad71b1dc1c9222d6d4410c092c2 from #587
> [Backport 1.x] Fix deserialization of S3 snapshot repository without settings (#587)

- CHANGELOG.md
> [1.x] Cut changelog for 1.7.1

- CHANGELOG.md
> [main] Cut changelog for 1.7.1

- DEVELOPER_GUIDE.md
- src/ApiGenerator/RestSpecDownloader.cs
Side effect of https://github.com/opensearch-project/opensearch-api-specification/pull/321
> Updated location of the API spec.

- docs/docfx.json
Update DocFx xref source as per https://github.com/dotnet/docfx/issues/9659
> Update DocFx xref source

- .github/workflows/backport.yml
- .github/workflows/delete_backport_branch.yml
Fix delete backport branch workflow
> Fix delete backport branch workflow

- .github/workflows/code-gen.yml
Create PRs automatically updating code-gen weekly
> Create PRs automatically updating code-gen weekly

- tests/Tests.YamlRunner/SkipList.fs
_Describe what this change achieves._
_List any issues this PR will resolve, e.g. Closes [...]._ 
> Skip failing YAML test due to unsupported operation

- src/OpenSearch.Client/OpenSearchClient.Indices.cs
Backport #717 via c2fdd5d1df4929000249d07ccdf2c8b21fd2fde6
> Fix Indices.BulkAsync summary (#717)

- .github/bump-version.sh
- .github/workflows/release-drafter.yml
- CHANGELOG.md
> Prepare for 1.8.0 release

- .github/bump-version.sh
- .github/workflows/release-drafter.yml
- CHANGELOG.md
> [Backport 1.x] Prepare for 1.8.0 release (#773)

- CHANGELOG.md
- build/scripts/scripts.fsproj
- src/ApiGenerator/ApiGenerator.csproj
- src/OpenSearch.Net.Auth.AwsSigV4/OpenSearch.Net.Auth.AwsSigV4.csproj
Backport #778 via 705c914b3f9b19a48b9279a5d7523eb2b37d8378
> [Backport 1.x] Dependabot upgrades

- OpenSearch.sln.DotSettings
- src/ApiGenerator/Domain/Specification/Deprecation.cs
- src/ApiGenerator/Generator/ApiEndpointFactory.cs
- src/ApiGenerator/opensearch-openapi.yaml
- src/OpenSearch.Client/_Generated/Descriptors.Cat.cs
- src/OpenSearch.Client/_Generated/OpenSearchClient.Cat.cs
- src/OpenSearch.Client/_Generated/Requests.Cat.cs
- src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Cat.cs
- src/OpenSearch.Net/_Generated/OpenSearchLowLevelClient.Cat.cs
Fix time type matching and normalize all deprecation versions
> Fix time type matching and normalize all deprecation versions

- src/ApiGenerator/Configuration/Overrides/GlobalOverrides.cs
- src/ApiGenerator/opensearch-openapi.yaml
Backport #728 via 3b8c0a6c67b6704a345b34070a2bc5f736e8af15
> [Backport 1.x] Re-generated client code using latest OpenSearch API specification (#728)

- CHANGELOG.md
- tests/Tests.ScratchPad/Tests.ScratchPad.csproj
> [Backport 1.x] Bump BenchMarkDotNet from 0.13.12 to 0.14.0 (#808)

- CHANGELOG.md
- build/scripts/scripts.fsproj
Bump Fake.IO.FileSystem, Fake.IO.Zip & Fake.Tools.Git to 6.1.1
> Bump Fake.IO.FileSystem, Fake.IO.Zip & Fake.Tools.Git to 6.1.1

- CHANGELOG.md
- src/ApiGenerator/ApiGenerator.csproj
> [Backport 1.x] Bump YamlDotNet from 16.1.0 to 16.1.3 (#816)

- src/ApiGenerator/Generator/ApiEndpointFactory.cs
- src/ApiGenerator/Generator/ApiGenerator.cs
- src/ApiGenerator/Generator/OpenApiUtils.cs
- src/ApiGenerator/opensearch-openapi.yaml
- src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Notifications.cs
Fix code generation enum handling
> Fix code generation enum handling

- CHANGELOG.md
- src/OpenSearch.Net/OpenSearch.Net.csproj
Removes packages for net 6+ as they can come from the framework
Closes #929 
> #929 conditionalize additional dependencies

- .github/workflows/integration.yml
- CHANGELOG.md
- build/scripts/Testing.fs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/IQueryContainer.cs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs
- src/OpenSearch.Client/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs
- src/OpenSearch.Client/QueryDsl/Query.cs
- src/OpenSearch.Client/QueryDsl/Specialized/Hybrid/HybridQuery.cs
- src/OpenSearch.Client/QueryDsl/Specialized/Knn/KnnQuery.cs
- src/OpenSearch.Client/QueryDsl/Specialized/Neural/NeuralQuery.cs
- src/OpenSearch.Client/QueryDsl/Visitor/DslPrettyPrintVisitor.cs
- src/OpenSearch.Client/QueryDsl/Visitor/QueryVisitor.cs
- src/OpenSearch.Client/QueryDsl/Visitor/QueryWalker.cs
- tests/Tests.Core/Extensions/EphemeralClusterExtensions.cs
- tests/Tests.YamlRunner/SkipList.fs
- tests/Tests/QueryDsl/QueryDslUsageTestsBase.cs
- tests/Tests/QueryDsl/Specialized/Hybrid/HybridQueryUsageTests.cs
- tests/Tests/QueryDsl/Specialized/Neural/NeuralQueryUsageTests.cs
Add support for hybrid query
Fixes #625 
Fixes #832
Fixes #927
> Add support for hybrid query
